# Generated by Django 5.2.5 on 2025-08-15 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.PositiveIntegerField()),
                (
                    "experience_years",
                    models.PositiveIntegerField(
                        help_text="Total teaching/research experience in years"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="faculty_photos/"
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        help_text="E.g. Potions, Charms, Defense Against the Dark Arts",
                        max_length=200,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("prof", "Professor"),
                            ("assoc", "Associate Professor"),
                            ("asst", "Assistant Professor"),
                            ("lect", "Lecturer"),
                            ("vis", "Visiting Faculty"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "other_roles",
                    models.CharField(
                        blank=True,
                        help_text="Additional responsibilities, e.g. House Head, Quidditch Coach",
                        max_length=200,
                    ),
                ),
                ("bio", models.TextField()),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("office_location", models.CharField(blank=True, max_length=100)),
                ("joined_on", models.DateField(auto_now_add=True)),
                (
                    "department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="faculty_members",
                        to="home.department",
                    ),
                ),
            ],
        ),
    ]
