# Generated by Django 5.2.5 on 2025-08-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_department_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faculty",
            name="role",
            field=models.CharField(
                choices=[
                    ("Professor", "Professor"),
                    ("Associate Professor", "Associate Professor"),
                    ("Assistant Professor", "Assistant Professor"),
                    ("Lecturer", "Lecturer"),
                    ("Visiting Faculty", "Visiting Faculty"),
                ],
                max_length=100,
            ),
        ),
    ]
