# Generated by Django 5.2.5 on 2025-08-16 09:47

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_faculty_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faculty",
            name="role",
        ),
        migrations.AddField(
            model_name="faculty",
            name="roles",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("Professor", "Professor"),
                    ("Associate Professor", "Associate Professor"),
                    ("Assistant Professor", "Assistant Professor"),
                    ("Lecturer", "Lecturer"),
                    ("Visiting Faculty", "Visiting Faculty"),
                    ("Headmaster", "Headmaster"),
                    ("Dy Headmistress", "Dy Headmistress"),
                    ("HoD", "HoD"),
                    ("Dean", "Dean"),
                ],
                default=[],
                max_length=200,
            ),
        ),
    ]
