# Generated by Django 5.2.5 on 2025-08-17 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_remove_faculty_role_faculty_roles"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faculty",
            name="department",
        ),
        migrations.DeleteModel(
            name="Department",
        ),
    ]
