# Generated by Django 5.2.5 on 2025-08-17 07:50

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_remove_faculty_department_delete_department"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("roll_number", models.CharField(max_length=20, unique=True)),
                ("age", models.PositiveIntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                (
                    "house",
                    models.CharField(
                        choices=[
                            ("GR", "Gryffindor"),
                            ("SL", "Slytherin"),
                            ("RB", "Ravenclaw"),
                            ("HB", "Hufflepuff"),
                        ],
                        max_length=2,
                    ),
                ),
                ("year", models.PositiveIntegerField(default=1)),
                (
                    "blood_status",
                    models.CharField(
                        choices=[
                            ("PB", "Pureblood"),
                            ("HB", "Half-blood"),
                            ("MB", "Muggle-born"),
                        ],
                        default="MB",
                        max_length=2,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="student_photos/"
                    ),
                ),
                ("joined_on", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="faculty",
            name="roles",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("Headmaster", "Headmaster"),
                    ("Dy Headmistress", "Dy Headmistress"),
                    ("Registrar", "Registrar"),
                    ("Dean-Placements", "Dean-Placements"),
                    ("Dean-Research & Development", "Dean-Research & Development"),
                    ("Dean-Academics", "Dean-Academics"),
                    ("Dean-Administration", "Dean-Administration"),
                    (
                        "Acad. Associate Dean-Student Affairs",
                        "Acad. Associate Dean-Student Affairs",
                    ),
                    (
                        "Admin. Associate Dean-Faculty Affairs",
                        "Admin. Associate Dean-Faculty Affairs",
                    ),
                    (
                        "Acad. Associate Dean-Curriculum",
                        "Acad. Associate Dean-Curriculum",
                    ),
                    (
                        "Admin. Associate Dean-Magic and Safety",
                        "Admin. Associate Dean-Magic and Safety",
                    ),
                    ("Controller of Examinations", "Controller of Examinations"),
                    ("Deputy Registrar", "Deputy Registrar"),
                    (
                        "Assistant Controller of Examinations",
                        "Assistant Controller of Examinations",
                    ),
                    ("HoD", "HoD"),
                    ("Professor", "Professor"),
                    ("Associate Professor", "Associate Professor"),
                    ("Assistant Professor", "Assistant Professor"),
                    ("Visiting Faculty", "Visiting Faculty"),
                    ("Lecturer", "Lecturer"),
                ],
                default=[],
                max_length=200,
            ),
        ),
    ]
