# Generated by Django 5.2.5 on 2025-08-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_subject_student_cgpa_student_sgpa1_student_sgpa2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="code",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
